import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Silk Evening Gown',
    price: 189.99,
    originalPrice: 249.99,
    description: 'A breathtaking emerald silk gown with a delicate cowl neck and elegant bias cut. Perfect for gala nights or sophisticated weddings.',
    category: 'Gowns',
    images: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop'],
    rating: 4.9,
    reviewsCount: 124,
    tags: ['Best Seller', 'Luxury'],
    inStock: true,
    colors: ['Emerald', 'Midnight Blue', 'Rose'],
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: '2',
    name: 'Cashmere Camel Coat',
    price: 299.99,
    description: 'Luxurious 100% cashmere coat with a structured silhouette and hand-finished seams. A timeless investment for every woman.',
    category: 'Outerwear',
    images: ['https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?q=80&w=800&auto=format&fit=crop'],
    rating: 4.8,
    reviewsCount: 86,
    tags: ['New'],
    inStock: true,
    colors: ['Camel', 'Ivory', 'Black'],
    sizes: ['S', 'M', 'L'],
  },
  {
    id: '3',
    name: 'Leather Pointed Stilettos',
    price: 159.99,
    originalPrice: 199.99,
    description: 'Sleek, handcrafted leather heels designed for both statement style and surprising daily comfort.',
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop'],
    rating: 4.7,
    reviewsCount: 210,
    tags: ['Trending'],
    inStock: true,
    colors: ['Red', 'Nude', 'Black'],
    sizes: ['36', '37', '38', '39', '40'],
  },
  {
    id: '4',
    name: 'Tailored Linen Blazer',
    price: 129.99,
    description: 'Crisp, lightweight linen blazer with a relaxed yet tailored fit. The ultimate transition piece for versatile styling.',
    category: 'Apparel',
    images: ['https://images.unsplash.com/photo-1548126032-079a0fb0099d?q=80&w=800&auto=format&fit=crop'],
    rating: 4.6,
    reviewsCount: 95,
    inStock: true,
    colors: ['Sand', 'Sage', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: '5',
    name: 'Diamond Stud Earrings',
    price: 499.00,
    description: 'Brilliant round-cut conflict-free diamonds set in 18k solid gold. A touch of every day brilliance.',
    category: 'Jewelry',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop'],
    rating: 5.0,
    reviewsCount: 45,
    tags: ['Premium'],
    inStock: true,
  },
  {
    id: '6',
    name: 'Vintage Silk Scarf',
    price: 45.00,
    originalPrice: 65.00,
    description: 'Hand-painted silk scarf featuring artisanal floral motifs. Soft, breathable, and infinitely chic.',
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=800&auto=format&fit=crop'],
    rating: 4.8,
    reviewsCount: 156,
    tags: ['Sale'],
    inStock: true,
  }
];

export const CATEGORIES = ['All', 'Gowns', 'Outerwear', 'Apparel', 'Shoes', 'Jewelry', 'Accessories'];
